package com.example.address.entity;

import java.util.ArrayList;
import java.util.List;

public class AddressDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public AddressDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJiscodeIsNull() {
            addCriterion("jiscode is null");
            return (Criteria) this;
        }

        public Criteria andJiscodeIsNotNull() {
            addCriterion("jiscode is not null");
            return (Criteria) this;
        }

        public Criteria andJiscodeEqualTo(String value) {
            addCriterion("jiscode =", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotEqualTo(String value) {
            addCriterion("jiscode <>", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeGreaterThan(String value) {
            addCriterion("jiscode >", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeGreaterThanOrEqualTo(String value) {
            addCriterion("jiscode >=", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLessThan(String value) {
            addCriterion("jiscode <", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLessThanOrEqualTo(String value) {
            addCriterion("jiscode <=", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeLike(String value) {
            addCriterion("jiscode like", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotLike(String value) {
            addCriterion("jiscode not like", value, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeIn(List<String> values) {
            addCriterion("jiscode in", values, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotIn(List<String> values) {
            addCriterion("jiscode not in", values, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeBetween(String value1, String value2) {
            addCriterion("jiscode between", value1, value2, "jiscode");
            return (Criteria) this;
        }

        public Criteria andJiscodeNotBetween(String value1, String value2) {
            addCriterion("jiscode not between", value1, value2, "jiscode");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldIsNull() {
            addCriterion("zipcode_old is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldIsNotNull() {
            addCriterion("zipcode_old is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldEqualTo(String value) {
            addCriterion("zipcode_old =", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldNotEqualTo(String value) {
            addCriterion("zipcode_old <>", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldGreaterThan(String value) {
            addCriterion("zipcode_old >", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldGreaterThanOrEqualTo(String value) {
            addCriterion("zipcode_old >=", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldLessThan(String value) {
            addCriterion("zipcode_old <", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldLessThanOrEqualTo(String value) {
            addCriterion("zipcode_old <=", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldLike(String value) {
            addCriterion("zipcode_old like", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldNotLike(String value) {
            addCriterion("zipcode_old not like", value, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldIn(List<String> values) {
            addCriterion("zipcode_old in", values, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldNotIn(List<String> values) {
            addCriterion("zipcode_old not in", values, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldBetween(String value1, String value2) {
            addCriterion("zipcode_old between", value1, value2, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeOldNotBetween(String value1, String value2) {
            addCriterion("zipcode_old not between", value1, value2, "zipcodeOld");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNull() {
            addCriterion("zipcode is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("zipcode =", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("zipcode <>", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("zipcode >", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("zipcode >=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("zipcode <", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("zipcode <=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("zipcode like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("zipcode not like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("zipcode in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("zipcode not in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("zipcode between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("zipcode not between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIsNull() {
            addCriterion("pref_kana is null");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIsNotNull() {
            addCriterion("pref_kana is not null");
            return (Criteria) this;
        }

        public Criteria andPrefKanaEqualTo(String value) {
            addCriterion("pref_kana =", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotEqualTo(String value) {
            addCriterion("pref_kana <>", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaGreaterThan(String value) {
            addCriterion("pref_kana >", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaGreaterThanOrEqualTo(String value) {
            addCriterion("pref_kana >=", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLessThan(String value) {
            addCriterion("pref_kana <", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLessThanOrEqualTo(String value) {
            addCriterion("pref_kana <=", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLike(String value) {
            addCriterion("pref_kana like", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotLike(String value) {
            addCriterion("pref_kana not like", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIn(List<String> values) {
            addCriterion("pref_kana in", values, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotIn(List<String> values) {
            addCriterion("pref_kana not in", values, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaBetween(String value1, String value2) {
            addCriterion("pref_kana between", value1, value2, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotBetween(String value1, String value2) {
            addCriterion("pref_kana not between", value1, value2, "prefKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNull() {
            addCriterion("city_kana is null");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNotNull() {
            addCriterion("city_kana is not null");
            return (Criteria) this;
        }

        public Criteria andCityKanaEqualTo(String value) {
            addCriterion("city_kana =", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotEqualTo(String value) {
            addCriterion("city_kana <>", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThan(String value) {
            addCriterion("city_kana >", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThanOrEqualTo(String value) {
            addCriterion("city_kana >=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThan(String value) {
            addCriterion("city_kana <", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThanOrEqualTo(String value) {
            addCriterion("city_kana <=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLike(String value) {
            addCriterion("city_kana like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotLike(String value) {
            addCriterion("city_kana not like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaIn(List<String> values) {
            addCriterion("city_kana in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotIn(List<String> values) {
            addCriterion("city_kana not in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaBetween(String value1, String value2) {
            addCriterion("city_kana between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotBetween(String value1, String value2) {
            addCriterion("city_kana not between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaIsNull() {
            addCriterion("street_kana is null");
            return (Criteria) this;
        }

        public Criteria andStreetKanaIsNotNull() {
            addCriterion("street_kana is not null");
            return (Criteria) this;
        }

        public Criteria andStreetKanaEqualTo(String value) {
            addCriterion("street_kana =", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaNotEqualTo(String value) {
            addCriterion("street_kana <>", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaGreaterThan(String value) {
            addCriterion("street_kana >", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaGreaterThanOrEqualTo(String value) {
            addCriterion("street_kana >=", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaLessThan(String value) {
            addCriterion("street_kana <", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaLessThanOrEqualTo(String value) {
            addCriterion("street_kana <=", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaLike(String value) {
            addCriterion("street_kana like", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaNotLike(String value) {
            addCriterion("street_kana not like", value, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaIn(List<String> values) {
            addCriterion("street_kana in", values, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaNotIn(List<String> values) {
            addCriterion("street_kana not in", values, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaBetween(String value1, String value2) {
            addCriterion("street_kana between", value1, value2, "streetKana");
            return (Criteria) this;
        }

        public Criteria andStreetKanaNotBetween(String value1, String value2) {
            addCriterion("street_kana not between", value1, value2, "streetKana");
            return (Criteria) this;
        }

        public Criteria andPrefIsNull() {
            addCriterion("pref is null");
            return (Criteria) this;
        }

        public Criteria andPrefIsNotNull() {
            addCriterion("pref is not null");
            return (Criteria) this;
        }

        public Criteria andPrefEqualTo(String value) {
            addCriterion("pref =", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotEqualTo(String value) {
            addCriterion("pref <>", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThan(String value) {
            addCriterion("pref >", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThanOrEqualTo(String value) {
            addCriterion("pref >=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThan(String value) {
            addCriterion("pref <", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThanOrEqualTo(String value) {
            addCriterion("pref <=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLike(String value) {
            addCriterion("pref like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotLike(String value) {
            addCriterion("pref not like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefIn(List<String> values) {
            addCriterion("pref in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotIn(List<String> values) {
            addCriterion("pref not in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefBetween(String value1, String value2) {
            addCriterion("pref between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotBetween(String value1, String value2) {
            addCriterion("pref not between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andStreetIsNull() {
            addCriterion("street is null");
            return (Criteria) this;
        }

        public Criteria andStreetIsNotNull() {
            addCriterion("street is not null");
            return (Criteria) this;
        }

        public Criteria andStreetEqualTo(String value) {
            addCriterion("street =", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotEqualTo(String value) {
            addCriterion("street <>", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThan(String value) {
            addCriterion("street >", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThanOrEqualTo(String value) {
            addCriterion("street >=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThan(String value) {
            addCriterion("street <", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThanOrEqualTo(String value) {
            addCriterion("street <=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLike(String value) {
            addCriterion("street like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotLike(String value) {
            addCriterion("street not like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetIn(List<String> values) {
            addCriterion("street in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotIn(List<String> values) {
            addCriterion("street not in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetBetween(String value1, String value2) {
            addCriterion("street between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotBetween(String value1, String value2) {
            addCriterion("street not between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("flag1 is null");
            return (Criteria) this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("flag1 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag1EqualTo(Byte value) {
            addCriterion("flag1 =", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotEqualTo(Byte value) {
            addCriterion("flag1 <>", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThan(Byte value) {
            addCriterion("flag1 >", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag1 >=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThan(Byte value) {
            addCriterion("flag1 <", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1LessThanOrEqualTo(Byte value) {
            addCriterion("flag1 <=", value, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1In(List<Byte> values) {
            addCriterion("flag1 in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotIn(List<Byte> values) {
            addCriterion("flag1 not in", values, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1Between(Byte value1, Byte value2) {
            addCriterion("flag1 between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag1NotBetween(Byte value1, Byte value2) {
            addCriterion("flag1 not between", value1, value2, "flag1");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNull() {
            addCriterion("flag2 is null");
            return (Criteria) this;
        }

        public Criteria andFlag2IsNotNull() {
            addCriterion("flag2 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag2EqualTo(Byte value) {
            addCriterion("flag2 =", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotEqualTo(Byte value) {
            addCriterion("flag2 <>", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThan(Byte value) {
            addCriterion("flag2 >", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag2 >=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThan(Byte value) {
            addCriterion("flag2 <", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2LessThanOrEqualTo(Byte value) {
            addCriterion("flag2 <=", value, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2In(List<Byte> values) {
            addCriterion("flag2 in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotIn(List<Byte> values) {
            addCriterion("flag2 not in", values, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2Between(Byte value1, Byte value2) {
            addCriterion("flag2 between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag2NotBetween(Byte value1, Byte value2) {
            addCriterion("flag2 not between", value1, value2, "flag2");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNull() {
            addCriterion("flag3 is null");
            return (Criteria) this;
        }

        public Criteria andFlag3IsNotNull() {
            addCriterion("flag3 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag3EqualTo(Byte value) {
            addCriterion("flag3 =", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotEqualTo(Byte value) {
            addCriterion("flag3 <>", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThan(Byte value) {
            addCriterion("flag3 >", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag3 >=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThan(Byte value) {
            addCriterion("flag3 <", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3LessThanOrEqualTo(Byte value) {
            addCriterion("flag3 <=", value, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3In(List<Byte> values) {
            addCriterion("flag3 in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotIn(List<Byte> values) {
            addCriterion("flag3 not in", values, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3Between(Byte value1, Byte value2) {
            addCriterion("flag3 between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag3NotBetween(Byte value1, Byte value2) {
            addCriterion("flag3 not between", value1, value2, "flag3");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNull() {
            addCriterion("flag4 is null");
            return (Criteria) this;
        }

        public Criteria andFlag4IsNotNull() {
            addCriterion("flag4 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag4EqualTo(Byte value) {
            addCriterion("flag4 =", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotEqualTo(Byte value) {
            addCriterion("flag4 <>", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThan(Byte value) {
            addCriterion("flag4 >", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag4 >=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThan(Byte value) {
            addCriterion("flag4 <", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4LessThanOrEqualTo(Byte value) {
            addCriterion("flag4 <=", value, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4In(List<Byte> values) {
            addCriterion("flag4 in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotIn(List<Byte> values) {
            addCriterion("flag4 not in", values, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4Between(Byte value1, Byte value2) {
            addCriterion("flag4 between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag4NotBetween(Byte value1, Byte value2) {
            addCriterion("flag4 not between", value1, value2, "flag4");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNull() {
            addCriterion("flag5 is null");
            return (Criteria) this;
        }

        public Criteria andFlag5IsNotNull() {
            addCriterion("flag5 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag5EqualTo(Byte value) {
            addCriterion("flag5 =", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotEqualTo(Byte value) {
            addCriterion("flag5 <>", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThan(Byte value) {
            addCriterion("flag5 >", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag5 >=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThan(Byte value) {
            addCriterion("flag5 <", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5LessThanOrEqualTo(Byte value) {
            addCriterion("flag5 <=", value, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5In(List<Byte> values) {
            addCriterion("flag5 in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotIn(List<Byte> values) {
            addCriterion("flag5 not in", values, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5Between(Byte value1, Byte value2) {
            addCriterion("flag5 between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag5NotBetween(Byte value1, Byte value2) {
            addCriterion("flag5 not between", value1, value2, "flag5");
            return (Criteria) this;
        }

        public Criteria andFlag6IsNull() {
            addCriterion("flag6 is null");
            return (Criteria) this;
        }

        public Criteria andFlag6IsNotNull() {
            addCriterion("flag6 is not null");
            return (Criteria) this;
        }

        public Criteria andFlag6EqualTo(Byte value) {
            addCriterion("flag6 =", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotEqualTo(Byte value) {
            addCriterion("flag6 <>", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6GreaterThan(Byte value) {
            addCriterion("flag6 >", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6GreaterThanOrEqualTo(Byte value) {
            addCriterion("flag6 >=", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6LessThan(Byte value) {
            addCriterion("flag6 <", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6LessThanOrEqualTo(Byte value) {
            addCriterion("flag6 <=", value, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6In(List<Byte> values) {
            addCriterion("flag6 in", values, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotIn(List<Byte> values) {
            addCriterion("flag6 not in", values, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6Between(Byte value1, Byte value2) {
            addCriterion("flag6 between", value1, value2, "flag6");
            return (Criteria) this;
        }

        public Criteria andFlag6NotBetween(Byte value1, Byte value2) {
            addCriterion("flag6 not between", value1, value2, "flag6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address_data
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 19 09:23:25 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address_data
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}