package com.example.address.entity;

public class AddressData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.id
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.jiscode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String jiscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.zipcode_old
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String zipcodeOld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.zipcode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.pref_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String prefKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.city_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String cityKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.street_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String streetKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.pref
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String pref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.city
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.street
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag1
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag2
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag3
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag4
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag5
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_data.flag6
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    private Byte flag6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.id
     *
     * @return the value of address_data.id
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.id
     *
     * @param id the value for address_data.id
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.jiscode
     *
     * @return the value of address_data.jiscode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getJiscode() {
        return jiscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.jiscode
     *
     * @param jiscode the value for address_data.jiscode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setJiscode(String jiscode) {
        this.jiscode = jiscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.zipcode_old
     *
     * @return the value of address_data.zipcode_old
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getZipcodeOld() {
        return zipcodeOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.zipcode_old
     *
     * @param zipcodeOld the value for address_data.zipcode_old
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setZipcodeOld(String zipcodeOld) {
        this.zipcodeOld = zipcodeOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.zipcode
     *
     * @return the value of address_data.zipcode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.zipcode
     *
     * @param zipcode the value for address_data.zipcode
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.pref_kana
     *
     * @return the value of address_data.pref_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getPrefKana() {
        return prefKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.pref_kana
     *
     * @param prefKana the value for address_data.pref_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setPrefKana(String prefKana) {
        this.prefKana = prefKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.city_kana
     *
     * @return the value of address_data.city_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getCityKana() {
        return cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.city_kana
     *
     * @param cityKana the value for address_data.city_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setCityKana(String cityKana) {
        this.cityKana = cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.street_kana
     *
     * @return the value of address_data.street_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getStreetKana() {
        return streetKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.street_kana
     *
     * @param streetKana the value for address_data.street_kana
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setStreetKana(String streetKana) {
        this.streetKana = streetKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.pref
     *
     * @return the value of address_data.pref
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getPref() {
        return pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.pref
     *
     * @param pref the value for address_data.pref
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setPref(String pref) {
        this.pref = pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.city
     *
     * @return the value of address_data.city
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.city
     *
     * @param city the value for address_data.city
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.street
     *
     * @return the value of address_data.street
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.street
     *
     * @param street the value for address_data.street
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag1
     *
     * @return the value of address_data.flag1
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag1
     *
     * @param flag1 the value for address_data.flag1
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag1(Byte flag1) {
        this.flag1 = flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag2
     *
     * @return the value of address_data.flag2
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag2
     *
     * @param flag2 the value for address_data.flag2
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag2(Byte flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag3
     *
     * @return the value of address_data.flag3
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag3() {
        return flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag3
     *
     * @param flag3 the value for address_data.flag3
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag3(Byte flag3) {
        this.flag3 = flag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag4
     *
     * @return the value of address_data.flag4
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag4() {
        return flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag4
     *
     * @param flag4 the value for address_data.flag4
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag4(Byte flag4) {
        this.flag4 = flag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag5
     *
     * @return the value of address_data.flag5
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag5() {
        return flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag5
     *
     * @param flag5 the value for address_data.flag5
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag5(Byte flag5) {
        this.flag5 = flag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_data.flag6
     *
     * @return the value of address_data.flag6
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public Byte getFlag6() {
        return flag6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_data.flag6
     *
     * @param flag6 the value for address_data.flag6
     *
     * @mbggenerated Thu Jul 19 09:23:25 JST 2018
     */
    public void setFlag6(Byte flag6) {
        this.flag6 = flag6;
    }
}